# Generated by Django 5.2.2 on 2025-06-05 02:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False, verbose_name='食物唯一标识')),
                ('name', models.CharField(max_length=100, verbose_name='食物名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='食物描述/备注/做法')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='食物图片链接')),
                ('calories', models.IntegerField(blank=True, help_text='建议非负数', null=True, verbose_name='一份热量（千卡/kcal）')),
                ('is_for_breakfast', models.BooleanField(default=False, verbose_name='是否适合早餐')),
                ('is_for_lunch', models.BooleanField(default=False, verbose_name='是否适合中餐')),
                ('is_for_afternoon_tea', models.BooleanField(default=False, verbose_name='是否适合下午茶')),
                ('is_for_dinner', models.BooleanField(default=False, verbose_name='是否适合晚餐')),
                ('is_for_supper', models.BooleanField(default=False, verbose_name='是否适合夜宵')),
                ('tags', models.CharField(blank=True, help_text='多个标签用逗号分隔', max_length=255, null=True, verbose_name='用户自定义标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='条目创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='条目最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '食物',
                'verbose_name_plural': '食物',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用餐记录唯一标识')),
                ('meal_type_recorded', models.CharField(choices=[('早餐', '早餐'), ('中餐', '中餐'), ('下午茶', '下午茶'), ('晚餐', '晚餐'), ('夜宵', '夜宵')], max_length=20, verbose_name='记录的餐次类型')),
                ('eaten_at_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='实际用餐日期和时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='额外备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='记录最后更新时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='daily_eat.foods', verbose_name='记录的具体食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用餐记录',
                'verbose_name_plural': '用餐记录',
                'ordering': ['-eaten_at_datetime'],
            },
        ),
    ]
