# Generated by Django 5.2.2 on 2025-06-05 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_eat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalorieGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories', models.IntegerField(blank=True, help_text='用户可能未设置目标', null=True, verbose_name='每日目标摄入热量（千卡/kcal）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='目标创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='目标最后更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_calorie_goal', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '每日热量目标',
                'verbose_name_plural': '每日热量目标',
            },
        ),
    ]
